### ISSUE TITLE
Investigate mysterious missing releases

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/ow-mod-db#210]
Some times, some releases are missing from the list when fetched. This triggers update notifications on prereleases, so I disabled prerelease notifications for now. For normal releases, it should only affect the download count, since the latest release is fetched with a separate endpoint.

**Comment by Raicuparta** [comment]
Seems to still affect the latest release api call. So yeah not sure what's going on

**Comment by Raicuparta** [comment]
example of a wrong commit: https://github.com/Raicuparta/ow-mod-db/commit/0c54a167d1e2b6670f8040e73608e4c31924e8b4

**Comment by Raicuparta** [comment]
Another one, latest release API returning a 404: https://pipelines.actions.githubusercontent.com/serviceHosts/db273f86-7523-4271-a103-82fd4254a248/_apis/pipelines/1/runs/68866/signedlogcontent/2?urlExpires=2022-04-01T20%3A48%3A59.3721376Z&urlSigningMethod=HMACV1&urlSignature=a81at%2FPguE5AcdeVT1hNi1ZY0c5qhp%2F7LBfZElQmBTY%3D

**Comment by Raicuparta** [comment]
Try using `@octokit/plugin-retry`

**Comment by Raicuparta** [comment]
I'm working around the missing releases by checking the latest release twice: via release list, and latest release API endpoints. But this doesn't work for prereleases (no latest prerelease endpoint)

**Comment by misternebula** [comment]
big batch of missing releases
![image](https://user-images.githubusercontent.com/41904486/164211675-57bea259-a5f7-4cb9-80b1-902b47bd7dcb.png)
https://github.com/Raicuparta/ow-mod-db/commit/fb2d279ebc0fee7b776ba66fd519129dcd7c98b9

**Comment by Raicuparta** [comment]
Adding this here for future reference. In commits 27bb22e, 09d515f, and 86092f9 I added the retry and throttle plugins to Octokit. This should make it recover from errors and avoid going over gh usage quotas. So far it seems to be working well, but gotta wait a bit longer to see if the errors ever pop up again.

**Comment by Raicuparta** [comment]
Bye
