### ISSUE TITLE
theirhomeworld

### ISSUE THREAD

**Issue by CreativeNameTxt** [Raicuparta/ow-mod-db#218]
### Mod uniqueName

CreativeNameTxt.theirhomeworld

### Mod name

their home world

### GitHub repository URL

https://github.com/CreativeNameTxt/their-home-world

### Parent uniqueName

xen.NewHorizons

### Utility mod

Is utility

**Comment by xen-42** [comment]
- Should not be marked as Utility
- Repo has no releases

You can reopen a new issue with those things corrected.
Bit of a nit-pick but probably would be nice to have the name use titles: Their Homeworld.
