### ISSUE TITLE
EotE Brighter Dreams

### ISSUE THREAD

**Issue by Heelio** [Raicuparta/ow-mod-db#42]
### Mod name

EotE Brighter Dreams

### GitHub repository URL

https://github.com/Heelio/EotE-Brighter-Dreams

### Mod uniqueName

Heelio.EotE-Brighter-Dreams

**Comment by Raicuparta** [comment]
I will add it to the list, but please be aware that the first image in your Readme.md will be used as the thumbnail on outerwildsmods.com.

**Comment by Heelio** [comment]
> I will add it to the list, but please be aware that the first image in your Readme.md will be used as the thumbnail on outerwildsmods.com.

Thanks, I just updated my Readme with a new image

**Comment by Heelio** [comment]
There is a mistake on the repo in the mods.json, must be Heelio/EotE-Brighter-Dreams

**Comment by Raicuparta** [comment]
Hey sorry about that, I fixed it.

**Comment by Raicuparta** [comment]
I had to fix your `uniqueName` in the database too, you provided one that's different to what you have in `manifest.json`. I changed it to `Heelio.EotEBrighterDreams`, which is what you have in the manifest.

Also, your mod has all the dependency dlls in the zip, which shouldn't happen. Maybe a bad config on the mod template.

**Comment by Heelio** [comment]
Oh sorry about that, I'll double check before the next update

**Comment by Raicuparta** [comment]
I made a PR to fix that dll issue, it was my fault: https://github.com/Heelio/EotE-Brighter-Dreams/pull/1

**Comment by Heelio** [comment]
Thanks! I updated my zip file
